// Fish Data
export const FISH_KEYS  = ["rohu", "catla", "mrigal", "tilapia", "prawns", "other"];
export const FISH_NAMES = ["Rohu", "Catla", "Mrigal", "Tilapia", "Prawns", "Other"];
export const FISH_EMOJI = { rohu: "🐟", catla: "🐡", mrigal: "🐠", tilapia: "🐟", prawns: "🦐", other: "🐾" };

// Languages
export const LANGS = [
  { code: "en", label: "English",  native: "English" },
  { code: "te", label: "Telugu",   native: "తెలుగు" },
  { code: "hi", label: "Hindi",    native: "हिंदी" },
  { code: "ta", label: "Tamil",    native: "தமிழ்" },
  { code: "or", label: "Odia",     native: "ଓଡ଼ିଆ" },
  { code: "kn", label: "Kannada",  native: "ಕನ್ನಡ" },
];

// Theme Colors
export const GREEN       = "#1a7a4a";
export const GREEN_DARK  = "#0d5c36";
export const GREEN_LIGHT = "#e8f7ef";
export const BG_COLOR    = "#f9fbf9";
export const BORDER_COLOR = "#e2e8f0";
export const TEXT_DARK   = "#1e293b";
export const TEXT_LIGHT  = "#64748b";

// Default Translation Dictionary for simple localization
export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to AquaSetu",
    tagline: "Your fish weighbridge assistant",
    selectLang: "Select Language / భాష ఎంచుకోండి",
    selectRole: "Choose your role",
    farmer: "Farmer",
    buyer: "Buyer",
    login: "Login / Registration",
    loginOnly: "Log In",
    signupOnly: "Sign Up",
    farmerPortal: "Farmer Portal",
    buyerPortal: "Buyer Portal",
    rolePrompt: "Choose how you want to proceed",
    goBack: "Change Role",
    deductionCalc: "Deduction Calculator",
    grossWeightLabel: "Total Gross Weight (kg)",
    priceLabel: "Price per kg (₹)",

    deductedRule: "5 kg / 100 kg deducted",
    fishLabel: "Fish",
    removeLabel: "Remove",
    grossWeightPlaceholder: "Total Gross Weight (kg)",
    pricePlaceholder: "Price per kg (₹)",
    addAnotherFish: "+ Add Another Fish", 
    enterPhone: "Enter Mobile Number",
    enterPin: "Enter Passcode/PIN",
    choosePin: "Choose Passcode/PIN (4-6 digits)",
    sendOTP: "Send Verification Code",
    enterOTP: "Enter OTP Code",
    verifyOTP: "Verify & Enter",
    profile: "Profile Setup",
    fullName: "Full Name",
    location: "Location (e.g. Nellore, AP)",
    experience: "Farming Experience (years)",
    save: "Save Profile",
    loading: "Loading...",
    weight: "Weight Scale",
    calc: "Calculator",
    history: "History",
    ai: "AquaAI Advisor",
    vehicles: "Vehicles",
    addBag: "Add Bag Weight",
    totalBags: "Total Bags",
    totalWeight: "Total Weight",
    average: "Avg Bag Weight",
    amount: "Total Amount",
    saveBatch: "Save Batch",
    liveScale: "Live Weight scale",
    historyLog: "History Log",
    weeklyStats: "Weekly Stats",
    askAI: "Ask AquaAI...",
    typeMsg: "Type a message...",
    send: "Send",
    regNo: "Registration No / Vehicle No",
    addVehicle: "Add Vehicle",
    activeVehicles: "Active Vehicles",
  },
  te: {
    welcome: "ఆక్వాసేతుకు స్వాగతం",
    tagline: "మీ చేపల బరువుల సహాయకుడు",
    selectLang: "భాషను ఎంచుకోండి",
    selectRole: "మీ పాత్రను ఎంచుకోండి",
    farmer: "రైతు",
    buyer: "కొనుగోలుదారు",
    login: "లాగిన్ / రిజిస్ట్రేషన్",
    loginOnly: "లాగిన్",
    signupOnly: "సైన్ అప్",
    farmerPortal: "రైతు పోర్టల్",
    buyerPortal: "కొనుగోలుదారు పోర్టల్",
    rolePrompt: "మీరు ఎలా కొనసాగాలనుకుంటున్నారో ఎంచుకోండి",
    goBack: "పాత్రను మార్చండి",
    deductionCalc: "మినహాయింపు క్యాలిక్యులేటర్",
    grossWeightLabel: "మొత్తం స్థూల బరువు (కిలోలు)",
    priceLabel: "ధర ప్రతి కిలో (₹)",
    deductedRule: "100 కిలోలకు 5 కిలోలు మినహాయింపు",
    fishLabel: "చేప",
    removeLabel: "తొలగించు",
    grossWeightPlaceholder: "మొత్తం బరువును నమోదు చేయండి",
    pricePlaceholder: "కిలో ధరను నమోదు చేయండి",
    addAnotherFish: "+ మరొక చేపను జోడించు",
    enterPhone: "మొబైల్ సంఖ్యను నమోదు చేయండి",
    enterPin: "పాస్‌కోడ్/పిన్ నమోదు చేయండి",
    choosePin: "పాస్‌కోడ్/పిన్‌ని ఎంచుకోండి (4-6 అంకెలు)",
    sendOTP: "ధృవీకరణ కోడ్ పంపండి",
    enterOTP: "OTP కోడ్ నమోదు చేయండి",
    verifyOTP: "ధృవీకరించండి",
    profile: "ప్రొఫైల్ సెటప్",
    fullName: "పూర్తి పేరు",
    location: "స్థలం (Nellore, AP)",
    experience: "వ్యవసాయ అనుభవం (సంవత్సరాలు)",
    save: "ప్రొఫైల్ సేవ్ చేయండి",
    loading: "లోడ్ అవుతోంది...",
    weight: "బరువు స్కేల్",
    calc: "క్యాలిక్యులేటర్",
    history: "చరిత్ర",
    ai: "ఆక్వాసేతు AI",
    vehicles: "వాహనాలు",
    addBag: "సంచి బరువును జోడించండి",
    totalBags: "మొత్తం సంచులు",
    totalWeight: "మొత్తం బరువు",
    average: "సగటు బరువు",
    amount: "మొత్తం ధర",
    saveBatch: "బ్యాచ్ సేవ్ చేయి",
    liveScale: "లైవ్ బరువు",
    historyLog: "చరిత్ర చిట్టా",
    weeklyStats: "వారపు గణాంకాలు",
    askAI: "ఆక్వాసేతు AI ని అడగండి...",
    typeMsg: "సందేశాన్ని టైప్ చేయండి...",
    send: "పంపు",
    regNo: "వాహనం నంబర్",
    addVehicle: "వాహనాన్ని జోడించు",
    activeVehicles: "సక్రియ వాహనాలు",
  },
  hi: {
    welcome: "एक्वासेतु में आपका स्वागत है",
    tagline: "मछली तौल सहायक",
    selectLang: "भाषा चुनें",
    selectRole: "अपनी भूमिका चुनें",
    farmer: "किसान",
    buyer: "खरीदार",
    login: "लॉगिन / पंजीकरण",
    loginOnly: "लॉग इन",
    signupOnly: "साइन अप",
    farmerPortal: "किसान पोर्टल",
    buyerPortal: "खरीदार पोर्टल",
    rolePrompt: "चुनें कि आप कैसे आगे बढ़ना चाहते हैं",
    goBack: "भूमिका बदलें",
    deductionCalc: "कटौती कैलकुलेटर",
    grossWeightLabel: "कुल सकल वजन (किग्रा)",
    priceLabel: "प्रति किग्रा मूल्य (₹)",
    deductedRule: "100 किलोग्राम पर 5 किलोग्राम की कटौती",
    fishLabel: "मछली",
    removeLabel: "हटाएं",
    grossWeightPlaceholder: "कुल वजन दर्ज करें",
    pricePlaceholder: "प्रति किग्रा मूल्य दर्ज करें",
    addAnotherFish: "+ दूसरी मछली जोड़ें",
    enterPhone: "मोबाइल नंबर दर्ज करें",
    enterPin: "पासकोड/पिन दर्ज करें",
    choosePin: "पासकोड/पिन चुनें (4-6 अंक)",
    sendOTP: "ओटीपी कोड भेजें",
    enterOTP: "ओटीपी दर्ज करें",
    verifyOTP: "सत्यापित करें",
    profile: "प्रोफ़ाइल सेटअप",
    fullName: "पूरा नाम",
    location: "स्थान (Nellore, AP)",
    experience: "खेती का अनुभव (वर्ष)",
    save: "प्रोफ़ाइल सहेजें",
    loading: "लोड हो रहा है...",
    weight: "वजन स्केल",
    calc: "कैलकुलेटर",
    history: "इतिहास",
    ai: "एक्वा एआई",
    vehicles: "वाहन",
    addBag: "बोरी का वजन जोड़ें",
    totalBags: "कुल बोरियां",
    totalWeight: "कुल वजन",
    average: "औसत वजन",
    amount: "कुल राशि",
    saveBatch: "बैच सहेजें",
    liveScale: "लाइव वजन स्केल",
    historyLog: "इतिहास लॉग",
    weeklyStats: "साप्ताहिक आँकड़े",
    askAI: "एक्वा एआई से पूछें...",
    typeMsg: "संदेश टाइप करें...",
    send: "भेजें",
    regNo: "वाहन नंबर",
    addVehicle: "वाहन जोड़ें",
    activeVehicles: "सक्रिय वाहन",
  }
};
